version: '3.8'
services:
  # Apache Web Server Service
  web:
    image: httpd:latest  # uses official Apache HTTP Image
    container_name: quiz-app-web
    ports: 
      - "8080:80"
    volumes: 
      - ./html:/usr/local/apache2/htdocs/ # Mount local html directory to document root
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf # Mount custom Apache conf file
    depends_on:
      - php
      #- db
    restart: unless-stopped
  
  # PHP-FPM Service
  php:
    build: ./php-fpm
    container_name: quiz-app-php
    volumes:
      # Mount same html direcory to PHP-FPM Document Root
      - ./html:/var/www/html 
    restart: unless-stopped

  # Database Service
  db: 
    image: mysql:8.0
    container_name: quiz-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: gemini
      MYSQL_PASSWORD: sql_password
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck: # <--- NEW HEALTHCHECK CONFIGURATION
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s # Give MySQL time to initialize before checking
    restart: unless-stopped
