version: '3.8'
services:
  # Apache Web Server Service
  web:
    image: httpd:latest  # uses official Apache HTTP Image
    container_name: quiz-app-web
    ports: 
      - "8080:80"
    volumes: 
      - ./application/public:/usr/local/apache2/htdocs/ # Mount local html directory to document root
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf # Mount custom Apache conf file
    depends_on:
      php: 
        condition: service_started
      db: 
        condition: service_healthy
    restart: unless-stopped
  
  # PHP-FPM Service
  php:
    build: ./php-fpm
    container_name: quiz-app-php
    volumes:
      # Map your local project root to a new directory in the container
      - .:/var/www/
      # This mapping is for the Apache webserver to serve files from
      - ./public:/var/www/html/
      # Mount PHP config file
      - ./php-config/php-custom-limits.ini:/usr/local/etc/php/conf.d/php-custom-limits.ini
    restart: unless-stopped

  # Database Service
  db: 
    image: mysql:8.0
    container_name: quiz-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: gemini
      MYSQL_PASSWORD: sql_password
    volumes:
      - ./db_data:/var/lib/mysql 
    healthcheck: # <--- NEW HEALTHCHECK CONFIGURATION
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s # Give MySQL time to initialize before checking
    restart: unless-stopped

  # phpMyAdmin Service
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: quiz-app-phpmyadmin
    ports: 
      - "8081:80"
    environment:
      # phpMyAdmin Environment DB
      PMA_HOST: db
      PMA_PORT: 3306
      # phpMyAdmin Configuration Storage Settings
      PMA_PMADB: pma 
      PMA_CONTROLHOST: db
      PMA_CONTROLPORT: 3306
      PMA_CONTROLUSER: root
      PMA_CONTROLPASS: password
      UPLOAD_LIMIT: 500M
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
